import type { Metadata } from "next";
import { Geist, Urbanist } from "next/font/google";
import "./globals.css";


const UrbanistFonts = Urbanist({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Eshop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${UrbanistFonts.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
