
import type { Metadata } from "next";
import {  Inter, Montserrat, Urbanist } from "next/font/google";
import "./globals.css";


const UrbanistFonts = Urbanist({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Eshop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${UrbanistFonts.className } ${inter.variable} antialiased`}
      >
    
          {children}
      </body>
    </html>
  );
}
